version: '3'
services:
    client:
        image: debian
        links:
            - wifirover
        depends_on:
            - wifirover
        networks:
            - lan

    wifirover:
        build: ./
        command: /root/unit_tests.php
        ports:
            - "8000:8000"
        networks:
            - lan
            - default
networks:
    lan:
        driver: overlay
        driver_opts:
            subnet: 192.168.22.0/24
